# Generated by Django 5.1.2 on 2024-10-24 01:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255)),
                ('percentage', models.IntegerField()),
                ('min_payment', models.IntegerField()),
                ('exp_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
