# Generated by Django 5.1.2 on 2024-10-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo_diskon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discentry',
            old_name='min_payment',
            new_name='valid_period',
        ),
        migrations.RemoveField(
            model_name='discentry',
            name='code',
        ),
        migrations.RemoveField(
            model_name='discentry',
            name='exp_date',
        ),
        migrations.RemoveField(
            model_name='discentry',
            name='percentage',
        ),
        migrations.AlterField(
            model_name='discentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
