# Generated by Django 5.1.2 on 2024-10-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo_diskon', '0003_discentry_code_discentry_min_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discentry',
            name='resto',
        ),
        migrations.AlterField(
            model_name='discentry',
            name='valid_period',
            field=models.DateField(),
        ),
    ]
