# Generated by Django 5.1.2 on 2024-10-25 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo_diskon', '0004_remove_discentry_resto_alter_discentry_valid_period'),
        ('restoran_makanan', '0002_auto_20241023_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='discentry',
            name='resto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restoran_makanan.rumahmakan'),
            preserve_default=False,
        ),
    ]
