# Generated by Django 5.1.2 on 2024-10-26 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo_diskon', '0006_alter_discentry_code_alter_discentry_resto'),
        ('restoran_makanan', '0002_auto_20241023_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discentry',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='discentry',
            name='resto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restoran_makanan.rumahmakan'),
        ),
    ]
