# Generated by Django 5.1.2 on 2024-10-27 10:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restoran_makanan', '0004_menu_harga'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RumahMakanFavorit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('favorit', models.BooleanField(default=False)),
                ('id_rumah_makan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restoran_makanan.rumahmakan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
