# Generated by Django 5.1.2 on 2024-10-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0005_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='foto_profil',
            field=models.ImageField(blank=True, default='profile_pics/default.png', null=True, upload_to='profile_pics/'),
        ),
    ]
