# Generated by Django 5.1.2 on 2024-10-27 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0008_foodpreference_searchhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchhistory',
            name='user_profile',
        ),
        migrations.DeleteModel(
            name='FoodPreference',
        ),
        migrations.DeleteModel(
            name='SearchHistory',
        ),
    ]
