# Generated by Django 5.1.1 on 2024-10-23 14:35

from django.db import migrations
from django.core.management import call_command

class Migration(migrations.Migration):
    def load_my_initial_data(apps, schema_editor):
        call_command("loaddata", "data_rumahmakan.json")
        call_command("loaddata", "data_menu.json")

    dependencies = [
        ('restoran_makanan', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_my_initial_data),
    ]
