# Generated by Django 5.1.2 on 2024-10-26 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restoran_makanan', '0002_auto_20241023_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='harga',
        ),
    ]
