# Generated by Django 5.1.2 on 2024-10-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoran_makanan', '0003_remove_menu_harga'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='harga',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
